### ISSUE TITLE
open links in new tab / no edit mode

### ISSUE THREAD

**Issue by u-name** [jez500/bender#4]
open links in new tab feature would be great.
also a no edit mode (only view mode) - perhaps as environment variabel in docker

**Comment by michealespinola** [comment]
If I can bandwagon this, I would love both options. 

Being able to open in new tabs by default would make dashboard checking a bit more streamlined (at least for my practices), and a no-edit mode would be very helpful for when using with smaller touchscreen interfaces.

I recently tried to use bender on my phone, and instead of scrolling the page, I kept just moving elements around.

**Comment by jez500** [comment]
This should be solved in `1.0.3` now https://hub.docker.com/r/jez500/bender/tags

Toggle of editing is done via the settings page, doing it via env var is a bit more complex but if enough demand I can look into it

**Comment by michealespinola** [comment]
Works great! Thank you!
